name: Scrape Profile Pages

on:
  workflow_dispatch:

jobs:
  scraping-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Scrapy
          pip install pandas
      
      - name: Running Script
        run: |
          python scrape.py
          python json2csv.py
      
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json *.csv
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
          
